### PR TITLE
Moves technical documentation into joint repo and sets up redirects.

### PR DESCRIPTION
**Pull request by berndverst**
We will redirect https://docs.cloud.gov to https://cloud.gov/docs
For this reason you will see aliases pages of the form `/docs/intro/*` which will then redirect to `/overview/*`

### CODE REVIEW

**Comment by berndverst** [comment]
@brittag would love for you to review

No content changes here, and the aliases actually do proper redirects to the new permanent URLs :)

**Comment by berndverst** [comment]
image
image

**Comment by berndverst** [comment]
Also note, there are still some references to the `cg-docs` repo. Given that we haven't decided yet whether we want to eventually move this site back over there I'm leaving the references in place at the moment.

But I can fix if we want in a later PR

**Comment by cnelson** [comment]
I have a couple of files to incorporate which the pipeline will use to deploy the app responsible for redirecting docs.cloud.gov.  Do you have a preference where I place them? If not I thought I'd just be explicit and place them in `redirects/docs.cloud.gov`

**Comment by berndverst** [comment]
@cnelson sure that sounds good. Want to add it in another PR after this is merged? And we can follow @brittag 's plan for combining the repos etc?

**Comment by berndverst** [comment]
For whoever reviews this:

You can ignore anything in `/content/`. Those are just files that were moved. No content changes. I did make sure to fix all links.

**Comment by berndverst** [comment]
Note to self -- help link is broken.

**Pull request closed without merging**
