### PR TITLE
New cg-site home design

### PR DESCRIPTION
**Pull request by thisisdano**
**Requires https://github.com/18F/cg-style/pull/169**

Updates look and feel of `cg-site` home to match new lightweight styles for the `cg-dashboard` app.

We're in the process of a major refresh of the dashboard for the coming planning increment. This design refresh uses the design motifs, colors, and typography from that redesign to give coherence across cloud.gov. I've attempted to pare down the motif overhead and give a more streamlined feel to the page. I'm focussing on clarity and solid trustworthy tone in addition to style conformity. (First draft of Design Principle here: https://github.com/18F/cg-product/wiki/Design-principles)

This is only the first phase. Docs will also get a refresh.

@berndverst @nickykrause @mogul This work crosses outside the Liberator domain into Skyporter (and beyond). Please consider this a first volley in a design discussion about the cg-site look and feel, and how that relates to the end-to-end look and feel of the cloud.gov experience. I suspect there's much more you all have in mind for this side of cloud.gov.

Discuss?

- - -

### CODE REVIEW

**Comment by thisisdano** [comment]
Oops, sorry @nickykrause. Meant to flag @nikzei!
:(

**Comment by vz3** [comment]
Pls hold on merge pending design review.

**Comment by vz3** [comment]
@thisisdano Just so you know my current thinking is that the first two color blocks need more work. The first feels very bright and the second is failing on color contrast accessibility

**Comment by thisisdano** [comment]
@vz3 
re: contrast — I tried to be pretty good wrt contrast (but sometimes do miss em). I this case, I get a contrast ratio of 4.51:1 for white on red, which checks out as OK for me (at least, contrast-wise) :)

**Comment by vz3** [comment]
Fails WCAG 2.0 AAA
http://webaim.org/resources/contrastchecker/

We should be reserving this red for error indication. I don't think it works in this large block application either.

**Comment by thisisdano** [comment]
I believe we only aim to pass AA.

**Comment by thisisdano** [comment]
In general, I agree wrt red and errors — but not necessarily on the product home. I think there are valid reasons to change from red, but not that red needs to be reserved for an error state (in this case).

**Pull request closed without merging**
